name: AAM
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aioeasywebdav=2.4.0=pyha770c72_0
  - aiohttp=3.8.1=py310h5764c6d_1
  - aiosignal=1.2.0=pyhd8ed1ab_0
  - amply=0.1.5=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - astroid=2.12.9=py310hff52083_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attmap=0.13.2=pyhd8ed1ab_0
  - attrs=22.1.0=pyh71513ae_1
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bcrypt=3.2.2=py310h5764c6d_0
  - black=22.6.0=py310hff52083_2
  - boto3=1.24.70=pyhd8ed1ab_0
  - botocore=1.27.70=pyhd8ed1ab_0
  - brotlipy=0.7.0=py310h5764c6d_1004
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.6.15.2=ha878542_0
  - cachetools=5.2.0=pyhd8ed1ab_0
  - certifi=2022.6.15.2=pyhd8ed1ab_0
  - cffi=1.15.1=py310h255011f_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=py310hff52083_0
  - coin-or-cbc=2.10.8=h3786ebc_0
  - coin-or-cgl=0.60.6=h6f57e76_2
  - coin-or-clp=1.17.7=hc56784d_2
  - coin-or-osi=0.108.7=h2720bb7_2
  - coin-or-utils=2.11.6=h202d8b1_2
  - coincbc=2.10.8=0_metapackage
  - colorama=0.4.5=pyhd8ed1ab_0
  - commonmark=0.9.1=py_0
  - configargparse=1.5.3=pyhd8ed1ab_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - cryptography=37.0.1=py310h9ce1e76_0
  - dataclasses=0.8=pyhc8e2a94_3
  - datrie=0.8.2=py310h6acc77f_3
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.5.1=pyhd8ed1ab_0
  - docutils=0.19=py310hff52083_0
  - dpath=2.0.6=py310hff52083_1
  - dropbox=11.34.0=pyhd8ed1ab_0
  - filechunkio=1.8=py_2
  - filelock=3.8.0=pyhd8ed1ab_0
  - flake8=5.0.4=pyhd8ed1ab_0
  - frozenlist=1.3.1=py310h5764c6d_0
  - ftputil=5.0.4=pyhd8ed1ab_0
  - future=0.18.2=py310hff52083_5
  - gitdb=4.0.9=pyhd8ed1ab_0
  - gitpython=3.1.27=pyhd8ed1ab_0
  - google-api-core=2.10.0=pyhd8ed1ab_0
  - google-api-python-client=2.60.0=pyhd8ed1ab_0
  - google-auth=2.11.0=pyh6c4a22f_0
  - google-auth-httplib2=0.1.0=pyhd8ed1ab_1
  - google-cloud-core=2.3.2=pyhd8ed1ab_0
  - google-cloud-storage=2.5.0=pyh6c4a22f_0
  - google-crc32c=1.1.2=py310he8fe98e_3
  - google-resumable-media=2.3.3=pyhd8ed1ab_0
  - googleapis-common-protos=1.56.4=py310hff52083_0
  - grpc-cpp=1.48.1=h30feacc_1
  - grpcio=1.48.1=py310hc32fa93_1
  - httplib2=0.20.4=pyhd8ed1ab_0
  - idna=3.3=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py310hff52083_0
  - importlib_resources=5.9.0=pyhd8ed1ab_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - isort=5.10.1=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jmespath=1.0.1=pyhd8ed1ab_0
  - jsonschema=4.16.0=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py310hff52083_0
  - lazy-object-proxy=1.7.1=py310h5764c6d_1
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libabseil=20220623.0=cxx17_h48a1fff_4
  - libblas=3.9.0=16_linux64_openblas
  - libcblas=3.9.0=16_linux64_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libgomp=12.1.0=h8d9b700_16
  - liblapack=3.9.0=16_linux64_openblas
  - liblapacke=3.9.0=16_linux64_openblas
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libprotobuf=3.21.5=h6239696_3
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.39.3=h753d276_0
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libuuid=2.32.1=h7f98852_1000
  - libzlib=1.2.12=h166bdaf_3
  - logmuse=0.2.6=pyh8c360ce_0
  - markupsafe=2.1.1=py310h5764c6d_1
  - mccabe=0.7.0=pyhd8ed1ab_0
  - multidict=6.0.2=py310h5764c6d_1
  - mypy_extensions=0.4.3=py310hff52083_5
  - nbformat=5.4.0=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - numpy=1.23.3=py310h53a5b5f_0
  - oauth2client=4.1.3=py_0
  - openssl=3.0.5=h166bdaf_2
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.4=py310h769672d_0
  - paramiko=2.11.0=pyhd8ed1ab_0
  - pathspec=0.10.1=pyhd8ed1ab_0
  - peppy=0.35.1=pyhd8ed1ab_0
  - pip=22.2.2=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - plac=1.3.5=pyhd8ed1ab_0
  - platformdirs=2.5.2=pyhd8ed1ab_1
  - pluggy=1.0.0=py310hff52083_3
  - ply=3.11=py_1
  - prettytable=3.4.1=pyhd8ed1ab_0
  - protobuf=4.21.5=py310hd8f1fbe_1
  - psutil=5.9.2=py310h5764c6d_0
  - pulp=2.6.0=py310hff52083_1
  - py=1.11.0=pyh6c4a22f_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycodestyle=2.9.1=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyflakes=2.5.0=pyhd8ed1ab_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pylint=2.15.2=pyhd8ed1ab_0
  - pynacl=1.5.0=py310h5764c6d_1
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyrsistent=0.18.1=py310h5764c6d_1
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=7.1.3=py310hff52083_0
  - python=3.10.6=ha86cf86_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.1=pyhd8ed1ab_0
  - python-irodsclient=1.1.4=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2022.2.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py310h5764c6d_4
  - ratelimiter=1.2.0=py_1002
  - re2=2022.06.01=h27087fc_0
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.1=pyhd8ed1ab_1
  - retry=0.9.2=py_0
  - rich=12.5.1=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - s3transfer=0.6.0=pyhd8ed1ab_0
  - setuptools=65.3.0=pyhd8ed1ab_1
  - setuptools-scm=7.0.5=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - slacker=0.14.0=py_0
  - smart_open=6.1.0=pyha770c72_1
  - smmap=3.0.5=pyh44b312d_0
  - snakemake=7.14.0=hdfd78af_0
  - snakemake-minimal=7.14.0=pyhdfd78af_0
  - stone=3.3.1=pyhd8ed1ab_0
  - stopit=1.1.2=py_0
  - tabulate=0.8.10=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.11.4=pyha770c72_0
  - toposort=1.7=pyhd8ed1ab_0
  - tqdm=4.64.1=pyhd8ed1ab_0
  - traitlets=5.3.0=pyhd8ed1ab_0
  - typing=3.10.0.0=pyhd8ed1ab_0
  - typing-extensions=4.3.0=hd8ed1ab_0
  - typing_extensions=4.3.0=pyha770c72_0
  - tzdata=2022c=h191b570_0
  - ubiquerg=0.6.2=pyhd8ed1ab_0
  - uritemplate=4.1.1=pyhd8ed1ab_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - veracitools=0.1.3=py_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.1=pyhd8ed1ab_0
  - wrapt=1.14.1=py310h5764c6d_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.7.2=py310h5764c6d_2
  - yte=1.5.1=py310hff52083_0
  - zipp=3.8.1=pyhd8ed1ab_0
  - zlib=1.2.12=h166bdaf_3
prefix: /home/nomad/.mambaforge/envs/AAM
